include:
- ./func/*
kind: ArchiveUploadSpec
name: func-zOUI

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: fn-get-nationality-0ade5ff3-06ce-473d-b831-e6ae8789fa79
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: env-get-nationality
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-zOUI
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-05-26T15:30:11Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: fn-get-nationality
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 3
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: env-get-nationality
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.get_enums
    packageref:
      name: fn-get-nationality-0ade5ff3-06ce-473d-b831-e6ae8789fa79
      namespace: default
  requestsPerPod: 10000
  resources: {}
