include:
- ./func/*
kind: ArchiveUploadSpec
name: func-N54x

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: fn-get-client-activity-0d04821c-5582-441e-8a52-488783cc3c01
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: env-get-client-activity
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-N54x
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-05-20T19:17:28Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: fn-get-client-activity
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 1
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: env-get-client-activity
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.get_enums
    packageref:
      name: fn-get-client-activity-0d04821c-5582-441e-8a52-488783cc3c01
      namespace: default
  requestsPerPod: 1
  resources: {}
