include:
- ./func/*
kind: ArchiveUploadSpec
name: func-OrTP

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: fn-get-nationality-ab9f1eec-c555-43c3-b531-b771f06592f1
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: env-get-nationality
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-OrTP
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-05-23T13:10:03Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: fn-get-nationality
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 1
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: env-get-nationality
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.get_enums
    packageref:
      name: fn-get-nationality-ab9f1eec-c555-43c3-b531-b771f06592f1
      namespace: default
  requestsPerPod: 1
  resources: {}
