apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: c4a7701c-c02e-4e7d-9ed9-4844bd99964e
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: fn-get-nationality
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /enum/nationality
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /enum/nationality
