apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: 558a56fc-7596-4542-a6c7-8c65754863e4
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: fn-get-client-activity
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /get_client_activity_type
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /get_client_activity_type
